apiVersion: v1
kind: Service
metadata:
  name: serivenginx
  labels:
    app: myenv1
spec:
  type: NodePort
  selector:
    app: myenv1
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 30080